### ISSUE TITLE
Manul keeps complaining about missing packages

### ISSUE THREAD

**Issue by annismckenzie** [kovetskiy/manul#10]
Just installed Manul – switching from govendor and my manual approach.

I removed the original vendor directory and just wanted to see what Manul does: `manul -v -Q`.

Output is as following:

``` bash
2016/05/17 09:46:34 cannot find package "google.golang.org/grpc" in any of:
    /Users/annismckenzie/git/GitHub/go/src/google.golang.org/grpc (from $GOROOT)
    /Users/annismckenzie/git/go/src/google.golang.org/grpc (from $GOPATH)
```

Not sure what's going (wr)on(g). Of course that package isn't there, I want Manul to handle this. So I did a manual `go get google.golang.org/grpc` but now it's complaining about the next package. Did I miss something? Using go1.6.2.

**Comment by gaplyk** [comment]
the problem is that this is not repo. repo is here: git@github:grpc/grpc-go.git

**Comment by annismckenzie** [comment]
Hmm, that's unfortunate. Still, what I'm missing in the error message is the line

```
  /Users/annismckenzie/git/go/src/git.[redacted-hostname]/[redacted-company]/[redacted-project-name]/vendor/google.golang.org/grpc (vendor tree)
```

Even if I manually add the submodule (which I did), Manul keeps complaining about other packages. The project is building and all dependencies are vendored [manually] as submodules and that error message somehow tells me that Manul is not looking into the `vendor/` folder.

The submodule section for the gRPC library is also correct:

```
[submodule "vendor/google.golang.org/grpc"]
    path = vendor/google.golang.org/grpc
    url = https://github.com/grpc/grpc-go
```

Right now it's complaining about ():

```
2016/05/20 21:21:18 cannot find package "[our-git-server]/alfatraining/accessToken" in any of:
    /Users/annismckenzie/git/GitHub/go/src/[our-git-server]/alfatraining/accessToken (from $GOROOT)
    /Users/annismckenzie/git/go/src/[our-git-server]/alfatraining/accessToken (from $GOPATH)
```

The submodule section for that package (sorry about the redacted stuff, it's internal):

```
[submodule "vendor/[our-git-server]/alfatraining/accessToken"]
    path = vendor/[our-git-server]/alfatraining/accessToken
    url = git@[our-git-server]:alfatraining/accessToken
```

That should work. It's git+ssh and the import path isn't different from the vendor folder structure. What am I not seeing? :)

**Comment by matthieudelaro** [comment]
same problem for me

**Comment by ghost** [comment]
i'm pretty sure this is caused by #13

**Comment by lingz** [comment]
same problem here

**Comment by sensimevanidus** [comment]
Same problem here

**Comment by kovetskiy** [comment]
pull-requests are welcome
