### ISSUE TITLE
Custom repository domains

### ISSUE THREAD

**Issue by dennwc** [kovetskiy/manul#13]
When trying to vendor packages like `google.golang.org/api` or `bazil.org/fuse` manul fails with timeout errors. This may be related to the use of `git+ssh` scheme instead of `https` (#8).

**Comment by kovetskiy** [comment]
Possible fix in #18.

**Comment by athoune** [comment]
The bug is still here : everything is ok with github.com url, but gopkg.in/yaml.v2 doesn't work.

**Comment by johansja** [comment]
This issue is caused by when missing `go-get` param when querying the site. Proposed fix in https://github.com/kovetskiy/manul/pull/25.

**Comment by kovetskiy** [comment]
Fixed due to #25.
