### ISSUE TITLE
cannot find package "golang_org/x/net/http2/hpack"

### ISSUE THREAD

**Issue by bydsky** [kovetskiy/manul#23]
->manul -Q
2016/09/05 17:11:00 cannot find package "golang_org/x/net/http2/hpack" in any of:
    /usr/local/go/src/golang_org/x/net/http2/hpack (from $GOROOT)
    /home/tiger/go/src/golang_org/x/net/http2/hpack (from $GOPATH)

->go version
go version go1.7 linux/amd64

**Comment by kovetskiy** [comment]
@bydsky how to reproduce?

**Comment by bydsky** [comment]
@kovetskiy In https://github.com/sideshow/apns2
Run manul -Q

It seems to me it's a bug in build.Import in go 1.7

**Comment by kovetskiy** [comment]
@bydsky Ok, I've fixed it, this error is occurring because since go1.7 net/http has own vendoring with golang_org packages.
