### ISSUE TITLE
Update subcommand needs `git submodule update --init`

### ISSUE THREAD

**Issue by mengzhuo** [kovetskiy/manul#28]
dependency on gopkg.in/ini.v1 shows vendored, however it's empty inside

```
manul -Q
gopkg.in/ini.v1                                   6f66b0e091edb3c7b380f7c4f0f884274d550b67

manul -I 
2016/12/30 23:19:40 skipping gopkg.in/ini.v1, already vendored

ls -alh vendor/gopkg.in/ini.v1
total 0
drwxr-xr-x  2 zhuo  staff    68B 12 30 22:00 .
drwxr-xr-x  3 zhuo  staff   102B 12 30 22:00 ..

manul -U -v gopkg.in/ini.v1
2016/12/30 23:25:17 exec ["git" "submodule" "status"]
2016/12/30 23:25:17 updating dependency gopkg.in/ini.v1
2016/12/30 23:25:17 exec ["git" "pull" "origin" "master"] in /Users/zhuo/go/src/github.com/mengzhuo/bla/vendor/gopkg.in/ini.v1
updated 1 dependency

ls vendor/gopkg.in/ini.v1 
// it's still empty

git submodule status
-6f66b0e091edb3c7b380f7c4f0f884274d550b67 vendor/gopkg.in/ini.v1
```

version: manul 1.4

**Comment by mengzhuo** [comment]
I see. it happened after I clone a new vendor based project from github.

I think it will be convenience that manul add ```git submodule update --init``` to manul -U
http://stackoverflow.com/questions/11358082/empty-git-submodule-folder-when-repo-cloned

**Comment by kovetskiy** [comment]
@mengzhuo Hi, thanks for reporting, can you please provide full step by step instruction for reproducing the bug?

**Comment by mengzhuo** [comment]
It's git's submodule issue.

```sh
mkdir -p  issue28/src/github.com/mengzhuo && cd issue28 && export GOPATH=`pwd`
cd github.com/mengzhuo
git clone https://github.com/mengzhuo/manul_issue28_base.git
cd manul_issue28_base
go run main.go # you got failed
```

**Comment by kovetskiy** [comment]
@mengzhuo git clone is not cloning submodules if special flag not passed (`--recursive`), try like this:
```
git  clone --recursive https://github.com/mengzhuo/manul_issue28_base.git
```
but actually you can use `go get` instead of `git clone`, because go get automatically runs `git submodule update --init` since go 1.6.

**Comment by mengzhuo** [comment]
@kovetskiy yes Thank you for your reply
