### ISSUE TITLE
Support projects with empty root

### ISSUE THREAD

**Issue by dennwc** [kovetskiy/manul#3]
If project has no Go files inside root directory `manul -Q` will exit with the following message:

```
no buildable Go source files in /path/to/repo
```

For go tool it is solved with `./...` argument which means walk current directory recursively.

**Comment by kovetskiy** [comment]
@dennwc can you give an example project?

And one question, what you think about case when two subprojects (subdirs) `./foo` and `./bar` depends of one external package `github.com/user/superlibrary`, how manul should handle this cases?

**Comment by dennwc** [comment]
@kovetskiy  [goprotobuf](https://github.com/gogo/protobuf) is one of the examples.

The logic stays the same. Lets assume we have `github.com/user/superproj` with two subdirs `foo` and `bar`. We can gather all dependencies recursively from both subdirs, and then vendor them under `github.com/user/superproj/vendor`.
Thus, there will be `github.com/user/superproj/vendor/github.com/user/superlibrary` directory with the dependency that you mentioned. Or I'm missing something and it will not work this way?

**Comment by ashb** [comment]
I think i have a similar but unrelated problem. The root of my project does have a .go file but most of the interesting code lives in sub-packages so `manual -Q` doesn't find them unless I cd into that dir

I would vote for something like the `./...` syntax/behaviour of common tools and how about this for semantics: if there is a `vendor/` in the current dir use it, otherwise use `vendor/` in the root of the git checkout?

**Comment by kovetskiy** [comment]
@dennwc @ashb sorry for the delay and thanks for reports about problem, I'll fix it today or tomorrow.

**Comment by djui** [comment]
I can chime in that my usecase is the following:

```
- cmd
  - name
    - main.go  # imports pkg/name/{foo,bar}
- pkg
  - name
    - foo
      - foo.go
    - bar
      - bar.go
```

And I want to determine all dependencies required for `cmd/name/main.go` and have the dependencies checked out in `/`, so would like to say `manul -I ./cmd/name`. See http://github.com/scraperwiki/seaeye or http://github.com/scraperwiki/hanoverd as examples.

**Comment by kovetskiy** [comment]
@dennwc @ashb @djui sorry for my lazy ass and please check it now, recursive importing should be supported.

Also I've added testcase:
https://github.com/kovetskiy/manul/commit/ae7b0d6312c0ed9c334300e5b8bde5b47c3a7c91

**Comment by ashb** [comment]
Wooot! 

Looks good apart from one exception - it includes the pacakge I'm "in" in the list (probably because I include subpackages in various places.)

i.e. when in `$GOPATH/src/github.com/ashb/myproject` it also lists (and tries to vendor) `github.com/ashb/myproject` (Using an explicit list of deps works fine though)

**Comment by djui** [comment]
Only had a quick look at it and I still have
1. One unexpected behaviour
2. One missing feature
3. Errors

I believe each one of these three could be its own issue. So please feel free to open (or let me open) issues for them:

### Unexpected behaviour

Why do some dependencies not have rev hashes? Especially when the output different on the same project but being in a different directory. Does blank mean HEAD? If, why does the output differ on the path I am in?

```
$ go get -u github.com/kovetskiy/manul
$ pwd
/Users/uwe/dev/go/src/github.com/scraperwiki/seaeye
$ manul -Q
github.com/google/go-github                7ec4e45f77474b3a7b7d9b7ef233a0cc8339ddf3
github.com/google/go-querystring           9235644dd9e52eeae6fa48efd539fdc351a0af53
github.com/gorilla/context                 a8d44e7d8e4d532b6a27a02dd82abb31cc1b01bd
github.com/gorilla/mux                     0eeaf8392f5b04950925b8a69fe70f110fa7cbfc
github.com/gorilla/websocket
github.com/scraperwiki/git-prep-directory  1b3e98bf866cafd17c7d6347708671fa86ff706d
github.com/scraperwiki/hookbot             2733e341aca2bd99447d86ec7a42c0d7449a5618
github.com/scraperwiki/seaeye
github.com/vaughan0/go-ini                 a98ad7ee00ec53921f08832bc06ecf7fd600e6a1
gopkg.in/yaml.v2                           a83829b6f1293c91addabc89d0571c246397bbf4

$ cd cmd/seaeye
$ pwd
$ manul -Q
github.com/google/go-github
github.com/google/go-querystring
github.com/gorilla/context
github.com/gorilla/mux
github.com/gorilla/websocket
github.com/scraperwiki/git-prep-directory
github.com/scraperwiki/hookbot
github.com/scraperwiki/seaeye
github.com/vaughan0/go-ini
gopkg.in/yaml.v2
```

### Missing feature

I would like to say `manul -Q ./cmd/...` but have the submodules being installed in the repo root, as Go vendor require that. Instead one has to currently do. This also leads to the incorrect behaviours:
1. Believes that the project needs a git submodule for itself.
   `2016/06/16 11:13:46 adding submodule for github.com/scraperwiki/seaeye` 
   `github.com/scraperwiki/seaeye/cmd/seaeye` already satisfies `github.com/scraperwiki/seaeye` dependency.
2. Believes that more dependencies are required than actually true:
   `2016/06/16 11:13:44 adding submodule for github.com/gorilla/websocket`
   I3s not a dependency on the command, only on a dependency's package.

### Errors

Manul seems to be a bit too greedy when it comes to unvendored nested dependencies. I don't need to all mentioned nested dependencies for my project, and therefor should be able to safely ignore them.

```
$ pwd
/Users/uwe/dev/go/src/fooproject
$ go get -u github.com/kovetskiy/manul
$ manul -Q
2016/06/16 10:57:42 cannot find package "github.com/erik/mixport/mixpanel" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/erik/mixport/mixpanel (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/erik/mixport/mixpanel (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/lib/pq" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/lib/pq (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/lib/pq (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/tealeg/xlsx" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/tealeg/xlsx (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/tealeg/xlsx (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/lib/pq" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/lib/pq (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/lib/pq (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/gorilla/sessions" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/gorilla/sessions (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/gorilla/sessions (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/tealeg/xlsx" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/tealeg/xlsx (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/tealeg/xlsx (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
2016/06/16 10:57:43 cannot find package "camlistore.org/pkg/magic" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/camlistore.org/pkg/magic (from $GOROOT)
    /Users/uwe/dev/go/src/camlistore.org/pkg/magic (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/go-ini/ini" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/go-ini/ini (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/go-ini/ini (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/gorilla/sessions" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/gorilla/sessions (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/gorilla/sessions (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/jmespath/go-jmespath" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/jmespath/go-jmespath (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/jmespath/go-jmespath (from $GOPATH)
2016/06/16 10:57:43 cannot find package "github.com/dukex/mixpanel" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/dukex/mixpanel (from $GOROOT)
    /Users/uwe/dev/go/src/github.com/dukex/mixpanel (from $GOPATH)
github.com/aws/aws-sdk-go                         7553d5227962c0f226768d0435881e99ec0cab35
github.com/codegangsta/cli                        a65b733b303f0055f8d324d805f393cd3e7a7904
github.com/elazarl/go-bindata-assetfs             d5cac425555ca5cf00694df246e04f05e6a55150
github.com/go-gorp/gorp                           0c9bc0918534d133cedb439a24adc7cbe66e4a9d
github.com/gorilla/context                        1c83b3eabd45b6d76072b66b746c20815fb2872d
github.com/gorilla/mux                            49c024275504f0341e5a9971eb7ba7fa3dc7af40
github.com/gorilla/websocket                      13e4d0621caa4d77fd9aa470ef6d7ab63d1a5e41
github.com/scraperwiki/hookbot                    c0c1d8ce3ef921976f5387da8d26b20f18e462e1
github.com/scraperwiki/tiny-ssl-reverse-proxy     b0d7ab0b34be266f5b88bfcff765e75f2154b954
gopkg.in/fsnotify.v1                              8611c35ab31c1c28aa903d33cf8b6e44a399b09e
fooproject
```

**Comment by dennwc** [comment]
@kovetskiy Thanks for the fix!

I want to add one thing to the list of potential issues. It seems like manul is not honoring the vendor directory by itself:

```
2016/06/16 13:08:38 cannot find package "github.com/coreos/etcd/mvcc/mvccpb" in any of:
        /usr/local/go/src/github.com/coreos/etcd/mvcc/mvccpb (from $GOROOT)
        /home/dennwc/Go/src/github.com/coreos/etcd/mvcc/mvccpb (from $GOPATH)
```

But at the same time I have a vendored version of the same package in `vendor/github.com/coreos/etcd`.

**Comment by kovetskiy** [comment]
@dennwc hm, ok, i'll check this case.
