### ISSUE TITLE
How to get specific SHAs and releases

### ISSUE THREAD

**Issue by klautcomputing** [kovetskiy/manul#35]
The title basically says it all. How do I get another sha then master and how do I get a specific release? Couldn't find info about that in the readme.

**Comment by kovetskiy** [comment]
Hi, thank you for reporting.

I just run `git checkout` in submodule, but you gave me good idea, I implemented this feature, now you can specify commit-ish using `=` delimiter, like `manul -I golang.org/x/blah=tag-1` or `manul -U golang.org/x/blah=old-blah`

Implemented in https://github.com/kovetskiy/manul/commit/9780bece0ac3b054d830f1a91222bd645ce4b11e


Feel free to close the issue if it works for you.

**Comment by klautcomputing** [comment]
Wow, that was ⚡️ fast. I am gonna try it on a couple of repos and report back later. Thank you 👍

**Comment by klautcomputing** [comment]
Trying to `go get` the current master gives me this error:

```go get github.com/kovetskiy/manul
# cd /home/klautcomputing/go/src/github.com/kovetskiy/manul; git submodule update --init --recursive
Submodule 'vendor/github.com/PuerkitoBio/goquery' (https://github.com/PuerkitoBio/goquery) registered for path 'vendor/github.com/PuerkitoBio/goquery'
Submodule 'vendor/github.com/kovetskiy/godocs' (https://github.com/kovetskiy/godocs) registered for path 'vendor/github.com/kovetskiy/godocs'
Submodule 'vendor/github.com/kovetskiy/lorg' (https://github.com/kovetskiy/lorg) registered for path 'vendor/github.com/kovetskiy/lorg'
fatal: No url found for submodule path 'vendor/github.com/reconquest/coproc.bash' in .gitmodules
package github.com/kovetskiy/manul: exit status 128```

**Comment by klautcomputing** [comment]
I just ran it again on a different machine and it worked, came back to the first one and it worked there as well 👍  Tested it and it works.

Thank you again for building this!
